language: generic

sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - curl -sSL https://github.com/sol/tinc/raw/master/get-tinc.sh | bash
  - export PATH=$HOME/.tinc/bin:$PATH
  - tinc --version
  - cabal --version
  - ghc --version
  - travis_retry cabal update
  - tinc

script:
  - cabal configure --enable-tests --ghc-options=-Werror
  - cabal build
  - cabal test

cache:
  directories:
    - $HOME/.tinc/cache
