name: MicroHs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sol/setup-MicroHs@nightly
      - run: mcabal install "--git=https://github.com/hspec/hspec --branch=micro-hs" --dir=hspec-core hspec-core
      - run: mcabal install hspec-discover
      - run: mcabal install "--git=https://github.com/hspec/hspec --branch=micro-hs" hspec
      - run: mcabal -r build
      - run: dist-mcabal/bin/mhs/spec
